### PR TITLE
darray: add ngli_darray_set()

### PR DESCRIPTION
**Pull request by jmoguillansky-gpsw**
Signed-off-by: Matthieu Bouron <matthieu.bouron@gmail.com>

### CODE REVIEW

**Comment by cboesch-gpsw** [comment]
What do you need this for?

**Comment by jmoguillansky-gpsw** [comment]
It’s a convenience api to set an item in an array.
We have api to get an item, we should probably have an api to set an item.
I think this is already signed/merged in vulkan , but not yet in master?

**Comment by cboesch-gpsw** [comment]
> It’s a convenience api to set an item in an array. We have api to get an item, we should probably have an api to set an item.

If it's not used, I don't see why. It also means it wouldn't be tested. I believe it was added because we needed it but don't anymore.

> I think this is already signed/merged in vulkan , but not yet in master?

It's been removed because it serves no purpose currently, afaict.

**Comment by jmoguillansky-gpsw** [comment]
you're right, we can close this

**Pull request closed without merging**
