### PR TITLE
change ngl_position from vec4 to vec3

### PR DESCRIPTION
**Pull request by jmoguillansky-gpsw**
Change ngl_position from vec4 to vec3, so that it matches the declaration in the node graph

### CODE REVIEW

**Comment by cboesch-gpsw** [comment]
Unfortunately I don't think you can split the commits here because the intermediate states will break: this is an API change

**Comment by jmoguillansky-gpsw** [comment]
sure I can merge the commits.  I mainly split the commits to simplify rebasing and rewriting history, etc.

**Comment by cboesch-gpsw** [comment]
> sure I can merge the commits. I mainly split the commits to simplify rebasing and rewriting history, etc.

every commit must be functional, be it only for `git bisect` to work as expected. When in doubt, use `git rebase master --exec "make test"`

**Comment by jmoguillansky-gpsw** [comment]
> > sure I can merge the commits. I mainly split the commits to simplify rebasing and rewriting history, etc.
> 
> every commit must be functional, be it only for `git bisect` to work as expected. When in doubt, use `git rebase master --exec "make tests"`

updated

**Comment by mbouron-gpsw** [comment]
I've updated the commit by adding some documentation adjustments and rebased it on top of master.

**Review by mbouron-gpsw — COMMENTED** [review]
LGTM.

**Review by mbouron-gpsw — APPROVED** [review]
Our main user confirmed it is OK to switch to vec3.

**Pull request merged**
