### PR TITLE
buffer: add offset param

### PR DESCRIPTION
**Pull request by jmoguillansky-gpsw**

### CODE REVIEW

**Review by cboesch-gpsw — APPROVED** [review]
This looks fine; just curious, do you plan to actually rely on this for something?

**Review by mbouron-gpsw — APPROVED** [review]

**Comment by jmoguillansky-gpsw** [comment]
> This looks fine; just curious, do you plan to actually rely on this for something?

Yes its important for updating a portion of a buffer

**Comment by cboesch-gpsw** [comment]
> > This looks fine; just curious, do you plan to actually rely on this for something?
> 
> Yes its important for updating a portion of a buffer

Yeah I understand; my question was whether you actually use that feature or not yet.

**Comment by jmoguillansky-gpsw** [comment]
> > > This looks fine; just curious, do you plan to actually rely on this for something?
> > 
> > 
> > Yes its important for updating a portion of a buffer
> 
> Yeah I understand; my question was whether you actually use that feature or not yet.

I don't believe I'm using it yet...  I think we need some logic at a higher level to see which portion of the buffer has changed, or expose this to the user at the node API level

**Pull request merged**
