### PR TITLE
Remove triangle_fan topology

### PR DESCRIPTION
**Pull request by cboesch-gpsw**

### CODE REVIEW

**Review by jmoguillansky-gpsw — APPROVED** [review]
Looks good.  Good idea to remove triangle-fan: since metal/dx12 don't directly support.  Can consider using triangle strips in the future.

**Comment by cboesch-gpsw** [comment]
> Can consider using triangle strips in the future.

That's a good point, not sure why I didn't do that in the first place. I'll update the PR.

**Comment by cboesch-gpsw** [comment]
Branch updated. I switched to triangle strip for all the quads, which admittedly simplifies the diff and the resulting code. OTOH I kept using triangles + indices for the node circle and the square2circle demo (since all the triangles recenter on the same vertex), and for the cropboard test with the indices (for variety/complexity).

**Review by jmoguillansky-gpsw — APPROVED** [review]

**Review by mbouron-gpsw — APPROVED** [review]
LGTM.

**Pull request merged**
