### PR TITLE
tools/build: automatically workaround a Python linking bug specific t…

### PR DESCRIPTION
**Pull request by cboesch-gpsw**
…o Ubuntu/Debian

The issue has been reported¹ months ago, and ignored.

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959945

### CODE REVIEW

**Review by jmoguillansky-gpsw — APPROVED** [review]
Thanks!  Much appreciated

**Review by mbouron-gpsw — APPROVED** [review]

**Comment by cboesch-gpsw** [comment]
I added a WIP/fixup commit: what workaround do you guys prefer? The vanilla patch or with the fixup?

**Comment by jmoguillansky-gpsw** [comment]
are you talking about .github/workflows/ci_linux.yml ?  How do we use that?

**Comment by cboesch-gpsw** [comment]
> are you talking about .github/workflows/ci_linux.yml ?

No, I'm talking about the "WIP this is a test" commit I added to the PR. It's an alternative way, probably more correct. Basically it emulates what would happen if Ubuntu/Debian fixed their packaging.

>  How do we use that?

The CI is the automation you can access in https://github.com/gopro/gopro-lib-node.gl/actions, or in the PR under "All checks have passed". But it's unrelated to what I was asking here.

**Comment by jmoguillansky-gpsw** [comment]
I'm ok with either approach, no strong preference.

I think its best to hide these changes from the makefile, and put it in a patch file that patches the makefile on certain distribution.  Before we run make we can run a script to apply patches.  This way the makefile is cleaner.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cboesch-gpsw** [comment]
> I'm ok with either approach, no strong preference. I think its best to hide these changes from the makefile, and put it in a patch file that patches the makefile on certain distribution. Before we run make we can run a script to apply patches. This way the makefile is cleaner.

But what exactly would you be patching here?

**Comment by jmoguillansky-gpsw** [comment]
Something like 

python-bug-workaround.patch:
ngl-tools/Makefile:
TOOLS += python serialize
+PYTHON_CFLAGS += ...
+PYTHON_LDFLAGS += ...

**Comment by jmoguillansky-gpsw** [comment]
Yes but the problem with this approach is that we need to keep updating the patch when we update the makefile.  
Another option is to use some script command like "sed" to patch the makefile as a preprocessing step

**Pull request merged**
